# Generated by ChatGPT on 2025-01-01
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("card_number", models.CharField(db_index=True, max_length=16)),
                ("expire", models.CharField(db_index=True, max_length=7)),
                ("phone", models.CharField(blank=True, db_index=True, max_length=15)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("expired", "Expired")],
                        max_length=10,
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={"ordering": ["card_number"]},
        ),
    ]
