# Generated by ChatGPT on 2025-01-01
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transfer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ext_id", models.CharField(db_index=True, max_length=64, unique=True)),
                ("sender_card_number", models.CharField(max_length=16)),
                ("receiver_card_number", models.CharField(max_length=16)),
                ("sender_card_expiry", models.CharField(max_length=7)),
                ("sender_phone", models.CharField(blank=True, max_length=15)),
                ("receiver_phone", models.CharField(blank=True, max_length=15)),
                ("sending_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("currency", models.PositiveSmallIntegerField()),
                ("receiving_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "state",
                    models.CharField(
                        choices=[("created", "Created"), ("confirmed", "Confirmed"), ("cancelled", "Cancelled")],
                        default="created",
                        max_length=10,
                    ),
                ),
                ("try_count", models.PositiveSmallIntegerField(default=0)),
                ("otp", models.CharField(blank=True, max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="Error",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.PositiveIntegerField(unique=True)),
                ("en", models.CharField(max_length=255)),
                ("ru", models.CharField(max_length=255)),
                ("uz", models.CharField(max_length=255)),
            ],
        ),
    ]
